### ISSUE TITLE
Hello, some question about training code

### ISSUE THREAD

**Issue by SamuelSue94** [chshin10/epinet#7]
I use imgaug to do data_augmentation, and train this model (input 9x9 images), and noticed that every epoch in model.fit() cost 100+ seconds and I run this on 2 TITAN V,and after 2600 epochs the results are bad, so I just want to know how you train this model, do you have a plan to release the full code? Since I was in this trouble for almost one month, more details would be appreciated.

**Comment by chshin10** [comment]
I upload train code now! It took more time than I thought.
Sorry for the late.

And I think 1-day is enough time for good result(my environment: i7-7700, one gtx1080ti, 32GB ram)
